export const dbProspectNames = [
  { id: 1, name: "nombre", label: "Nombre de empresa" },
  { id: 14, name: "nit", label: "Número de identificación tributaria (NIT)" },
  { id: 2, name: "telefono", label: "Teléfono de la empresa" },
  { id: 13, name: "correo", label: "Correo electrónico de la empresa" },
  { id: 3, name: "vertical", label: "Sector" },
  { id: 4, name: "propiedad", label: "Propiedad (privada, publica, etc...)" },
  { id: 15, name: "representante", label: "Representante legal" },
  { id: 5, name: "empleados", label: "Número de empleados" },
  { id: 6, name: "ingresos_anuales", label: "Ingresos Anuales" },
  { id: 12, name: "nombre_contacto", label: "Nombre de contacto principal" },
  { id: 21, name: "telf_contacto", label: "Teléfono de contacto identificado" },
  { id: 22, name: "email_contacto", label: "Correo de contacto principal" },
  { id: 7, name: "web", label: "Sitio web propio de la empresa" },
  { id: 8, name: "linkedin", label: "Perfil de LinkedIn" },
  { id: 9, name: "facebook", label: "Página de Facebook" },
  { id: 10, name: "instagram", label: "Perfil de Instagram" },
  { id: 11, name: "twitter", label: "Perfil de Twitter" },
  { id: 16, name: "calle", label: "Dirección - Calle" },
  { id: 17, name: "ciudad", label: "Dirección - Ciudad" },
  { id: 18, name: "estado", label: "Dirección - Estado" },
  { id: 19, name: "codigoPostal", label: "Dirección - Código postal" },
  { id: 20, name: "pais", label: "Dirección - País" },
];
