const actions = {};

// Contactos
actions.GET_CONTACTOS = "GET_CONTACTOS";
actions.CREATE_CONTACTO = "CREATE_CONTACTO";
actions.UPDATE_CONTACTO = "UPDATE_CONTACTO";
actions.DELETE_CONTACTO = "DELETE_CONTACTO";

// Empleados
actions.GET_EMPLEADOS = "GET_EMPLEADOS";
actions.CREATE_EMPLEADO = "CREATE_EMPLEADO";
actions.UPDATE_EMPLEADO = "UPDATE_EMPLEADO";
actions.DELETE_EMPLEADO = "DELETE_EMPLEADO";
actions.GET_PROSPECTOS = "GET_PROSPECTOS";
actions.GET_CLIENTES = "GET_CLIENTES";

// Empresas
actions.GET_EMPRESAS = "GET_EMPRESAS";
actions.CREATE_EMPRESA = "CREATE_EMPRESA";
actions.UPDATE_EMPRESA = "UPDATE_EMPRESA";
actions.DELETE_EMPRESA = "DELETE_EMPRESA";

export default actions;
