const actions = {};

// Modals
actions.OPEN_DELETE = "OPEN_DELETE";
actions.OPEN_UPDATE = "OPEN_UPDATE";
actions.OPEN_DETAIL = "OPEN_DETAIL";
actions.CLOSE_MODALS = "CLOSE_MODALS";

// Contactos
actions.GET_CONTACTOS = "GET_CONTACTOS";
actions.CREATE_CONTACTO = "CREATE_CONTACTO";
actions.UPDATE_CONTACTO = "UPDATE_CONTACTO";
actions.DELETE_CONTACTO = "DELETE_CONTACTO";

// Empleados
actions.GET_EMPLEADOS = "GET_EMPLEADOS";
actions.CREATE_EMPLEADO = "CREATE_EMPLEADO";
actions.UPDATE_EMPLEADO = "UPDATE_EMPLEADO";
actions.DELETE_EMPLEADO = "DELETE_EMPLEADO";

// Productos
actions.GET_PRODUCTOS = "GET_PRODUCTOS";
actions.CREATE_PRODUCTO = "CREATE_PRODUCTO";
actions.UPDATE_PRODUCTO = "UPDATE_PRODUCTO";
actions.DELETE_PRODUCTO = "DELETE_PRODUCTO";

// Empresas
actions.GET_EMPRESAS = "GET_EMPRESAS";
actions.CREATE_EMPRESA = "CREATE_EMPRESA";
actions.UPDATE_EMPRESA = "UPDATE_EMPRESA";
actions.DELETE_EMPRESA = "DELETE_EMPRESA";
actions.GET_PROSPECTOS = "GET_PROSPECTOS";
actions.GET_CLIENTES = "GET_CLIENTES";

export default actions;
