const actions = {};

// Global
actions.SET_IS_AUTH = "SET_IS_AUTH";
actions.SET_DETAIL_VIEW_TYPE = "SET_DETAIL_VIEW_TYPE";

// Email
actions.SEND_EMAIL = "SEND_EMAIL";

// Modals
actions.SET_SELECTED = "SET_SELECTED";
actions.TOGGLE_DELETE = "TOGGLE_DELETE";
actions.TOGGLE_UPDATE = "TOGGLE_UPDATE";
actions.TOGGLE_DELETE_MANY = "TOGGLE_DELETE_MANY";
actions.CLOSE_MODALS = "CLOSE_MODALS";

// Contactos
actions.GET_CONTACTOS = "GET_CONTACTOS";
actions.GET_SINGLE_CONTACTO = "GET_SINGLE_CONTACTO";
actions.CREATE_CONTACTO = "CREATE_CONTACTO";
actions.UPDATE_CONTACTO = "UPDATE_CONTACTO";
actions.DELETE_CONTACTO = "DELETE_CONTACTO";

// Empleados
actions.GET_EMPLEADOS = "GET_EMPLEADOS";
actions.GET_SINGLE_EMPLEADO = "GET_SINGLE_EMPLEADOS";
actions.CREATE_EMPLEADO = "CREATE_EMPLEADO";
actions.UPDATE_EMPLEADO = "UPDATE_EMPLEADO";
actions.DELETE_EMPLEADO = "DELETE_EMPLEADO";

// Productos
actions.GET_PRODUCTOS = "GET_PRODUCTOS";
actions.GET_SINGLE_PRODUCTO = "GET_SINGLE_PRODUCTO";
actions.CREATE_PRODUCTO = "CREATE_PRODUCTO";
actions.UPDATE_PRODUCTO = "UPDATE_PRODUCTO";
actions.DELETE_PRODUCTO = "DELETE_PRODUCTO";

// Empresas
actions.GET_EMPRESAS = "GET_EMPRESAS";
actions.GET_PROSPECTOS = "GET_PROSPECTOS";
actions.GET_CLIENTES = "GET_CLIENTES";
actions.GET_SINGLE_EMPRESA = "GET_SINGLE_EMPRESA";
actions.CREATE_EMPRESA = "CREATE_EMPRESA";
actions.UPDATE_EMPRESA = "UPDATE_EMPRESA";
actions.DELETE_EMPRESA = "DELETE_EMPRESA";

// Oportunidades
actions.GET_OPORTUNIDADES = "GET_OPORTUNIDADES";

export default actions;
